In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('train.csv', sep=',')
dataPredict = pd.read_csv('test.csv', sep=',')
pd.options.display.max_columns = None
pd.set_option('expand_frame_repr', False)
data.head()

  job_level  job_duration_in_current_job_level person_level  job_duration_in_current_person_level  job_duration_in_current_branch Employee_type Employee_status  gender   age marital_status_maried(Y/N)  number_of_dependences  number_of_dependences (male)  number_of_dependences (female) Education_level   GPA year_graduated  job_duration_as_permanent_worker  job_duration_from_training  branch_rotation  job_rotation  assign_of_otherposition  annual leave  sick_leaves  Best Performance  Avg_achievement_%  Last_achievement_%  Achievement_above_100%_during3quartal achievement_target_1 achievement_target_2 achievement_target_3
0      JG05                               8.00         PG06                                  8.00                            0.50     RM_type_A       Permanent  Female  1964                          Y                      3                             1                               2         level_4  2.32           1987                              30.0                          30                9             7                        0             8            0                 0              68.85               72.53                                    0.0      achiev_50%-100%         achiev_< 50%              reached
1      JG04                               5.17         PG04                                  2.00                            1.25     RM_type_A       Permanent    Male  1979                          Y                      3                             2                               1         level_4  3.25           2001                              15.0                          16                7             7                        9             3            0                 0              94.81              101.13                                    3.0      achiev_50%-100%      achiev_50%-100%              reached
2      JG04                               1.83         PG03                                  1.83                            1.50     RM_type_A       Permanent    Male  1980                          Y                      1                             0                               1         level_5  3.23           2007                              15.0                          15                9             9                        0             6            0                 0              72.82               71.30                                    0.0     achiev_100%-150%         achiev_< 50%          not_reached
3      JG04                               7.92         PG04                                  4.00                            0.17     RM_type_A       Permanent    Male  1984                          Y                      0                             0                               0         level_3  0.00           2006                               8.0                           8                5             5                        0             3            0                 0              86.89               90.09                                    2.0      achiev_50%-100%      achiev_50%-100%          not_reached
4      JG04                               1.83         PG03                                  1.83                            2.08     RM_type_A       Permanent    Male  1984                          Y                      1                             0                               1             NaN   NaN            NaN                               7.0                           7                4             6                       11             2            1                 1              95.17              100.72                                    2.0         achiev_< 50%         achiev_> 1.5          not_reached

In [2]:
fdata = data.drop(['Education_level',
                   'GPA',
                   'year_graduated',
                   
                   'Avg_achievement_%',
                   'Last_achievement_%',
                   'Achievement_above_100%_during3quartal',
                   'achievement_target_1',
                   'achievement_target_2',
                   'achievement_target_3'], 
                  axis=1)


fdata2 = dataPredict.drop(['Education_level',
                   'GPA',
                   'year_graduated',
                   
                   'Avg_achievement_%',
                   'Last_achievement_%',
                   'Achievement_above_100%_during3quartal',
                   'achievement_target_1',
                   'achievement_target_2',
                   'achievement_target_3'], 
                  axis=1)

In [3]:
f1data = fdata.dropna()
f1data_label = f1data['Best Performance']
f1data = f1data.drop('Best Performance', axis = 1)
data_combine = f1data.append(fdata2)
print(len(data_combine))
print(len(f1data))
print(data.isnull().sum())
f1data.head()

25938
19938
job_level                                   0
job_duration_in_current_job_level           0
person_level                                0
job_duration_in_current_person_level        0
job_duration_in_current_branch              0
Employee_type                              12
Employee_status                             0
gender                                      0
age                                         0
marital_status_maried(Y/N)                  0
number_of_dependences                       0
number_of_dependences (male)                0
number_of_dependences (female)              0
Education_level                          3608
GPA                                      3503
year_graduated                           3503
job_duration_as_permanent_worker         2055
job_duration_from_training                  0
branch_rotation                             0
job_rotation                                0
assign_of_otherposition                     0
annual leave                                0
sick_leaves                                 0
Best Performance                            0
Avg_achievement_%                        6289
Last_achievement_%                       6302
Achievement_above_100%_during3quartal    6302
achievement_target_1                     6727
achievement_target_2                     6727
achievement_target_3                     6727
dtype: int64

  job_level  job_duration_in_current_job_level person_level  job_duration_in_current_person_level  job_duration_in_current_branch Employee_type Employee_status  gender   age marital_status_maried(Y/N)  number_of_dependences  number_of_dependences (male)  number_of_dependences (female)  job_duration_as_permanent_worker  job_duration_from_training  branch_rotation  job_rotation  assign_of_otherposition  annual leave  sick_leaves
0      JG05                               8.00         PG06                                  8.00                            0.50     RM_type_A       Permanent  Female  1964                          Y                      3                             1                               2                              30.0                          30                9             7                        0             8            0
1      JG04                               5.17         PG04                                  2.00                            1.25     RM_type_A       Permanent    Male  1979                          Y                      3                             2                               1                              15.0                          16                7             7                        9             3            0
2      JG04                               1.83         PG03                                  1.83                            1.50     RM_type_A       Permanent    Male  1980                          Y                      1                             0                               1                              15.0                          15                9             9                        0             6            0
3      JG04                               7.92         PG04                                  4.00                            0.17     RM_type_A       Permanent    Male  1984                          Y                      0                             0                               0                               8.0                           8                5             5                        0             3            0
4      JG04                               1.83         PG03                                  1.83                            2.08     RM_type_A       Permanent    Male  1984                          Y                      1                             0                               1                               7.0                           7                4             6                       11             2            1

In [4]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
LE = LabelEncoder()

data_combine['job_level'] = LE.fit_transform(data_combine['job_level'])
data_combine['person_level'] = LE.fit_transform(data_combine['person_level'])
data_combine['Employee_type'] = LE.fit_transform(data_combine['Employee_type'])
data_combine['Employee_status'] = LE.fit_transform(data_combine['Employee_status'])
data_combine['gender'] = LE.fit_transform(data_combine['gender'])
data_combine['age'] = LE.fit_transform(data_combine['age'])
data_combine['marital_status_maried(Y/N)'] = LE.fit_transform(data_combine['marital_status_maried(Y/N)'])
data_combine

      job_level  job_duration_in_current_job_level  person_level  job_duration_in_current_person_level  job_duration_in_current_branch  Employee_type  Employee_status  gender  age  marital_status_maried(Y/N)  number_of_dependences  number_of_dependences (male)  number_of_dependences (female)  job_duration_as_permanent_worker  job_duration_from_training  branch_rotation  job_rotation  assign_of_otherposition  annual leave  sick_leaves
0             2                               8.00             5                                  8.00                            0.50              0                0       0    1                           1                      3                             1                               2                              30.0                          30                9             7                        0             8            0
1             1                               5.17             3                                  2.00                            1.25              0                0       1   16                           1                      3                             2                               1                              15.0                          16                7             7                        9             3            0
2             1                               1.83             2                                  1.83                            1.50              0                0       1   17                           1                      1                             0                               1                              15.0                          15                9             9                        0             6            0
3             1                               7.92             3                                  4.00                            0.17              0                0       1   21                           1                      0                             0                               0                               8.0                           8                5             5                        0             3            0
4             1                               1.83             2                                  1.83                            2.08              0                0       1   21                           1                      1                             0                               1                               7.0                           7                4             6                       11             2            1
...         ...                                ...           ...                                   ...                             ...            ...              ...     ...  ...                         ...                    ...                           ...                             ...                               ...                         ...              ...           ...                      ...           ...          ...
5995          0                               2.75             0                                  2.75                            2.75              1                0       1   24                           0                      0                             0                               0                               3.0                           3                1             1                        0             1            0
5996          1                               1.17             2                                  1.17                            0.50              1                0       1   24                           1                      1                             0                               1                               4.0                           4                3             3                        0             0            0
5997          1                               1.83             2                                  1.83                            1.92              0                0       1   23                           1                      2                             1                               1                               7.0                           7                5             3                        0             3            0
5998          1                               1.92             2                                  1.92                            1.25              0                0       1   21                           1                      0                             0                               0                               6.0                           6                5             3                        0             1            0
5999          1                               2.00             2                                  2.00                            0.42              0                0       0   26                           1                      0                             0                               0                               4.0                           4                3             2                        0             4            0

[25938 rows x 20 columns]

In [101]:
pred_real_data = data_combine[len(data_combine)-6000:]
data_for_train_test = data_combine[:len(data_combine)-6000]
data_for_train_test = data_for_train_test.assign(best_performance=f1data_label.values)

In [6]:
import h2o

# Number of threads, nthreads = -1, means use all cores on your machine
# max_mem_size is the maximum memory (in GB) to allocate to H2O
h2o.init(nthreads = 2, max_mem_size = 3)

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
  Starting server from E:\Anaconda\envs\project1\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\ASUSA4~1\AppData\Local\Temp\tmp2bp9boh6
  JVM stdout: C:\Users\ASUSA4~1\AppData\Local\Temp\tmp2bp9boh6\h2o_Rizky_Saputra_started_from_python.out
  JVM stderr: C:\Users\ASUSA4~1\AppData\Local\Temp\tmp2bp9boh6\h2o_Rizky_Saputra_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ---------------------------------------------------------
H2O_cluster_uptime:         08 secs
H2O_cluster_timezone:       Asia/Bangkok
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.0.2
H2O_cluster_version_age:    1 month
H2O_cluster_name:           H2O_from_python_Rizky_Saputra_8r9fa5
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.9 final
--------------------------  ---------------------------------------------------------

In [7]:
dataH2o = h2o.H2OFrame(data_for_train_test)

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [100]:
dataH2o['best_performance'] = dataH2o['best_performance'].asfactor()
dataH2o['best_performance'].levels()
dataH2o

job_level,job_duration_in_current_job_level,person_level,job_duration_in_current_person_level,job_duration_in_current_branch,Employee_type,Employee_status,gender,age,marital_status_maried(Y/N),number_of_dependences,number_of_dependences (male),number_of_dependences (female),job_duration_as_permanent_worker,job_duration_from_training,branch_rotation,job_rotation,assign_of_otherposition,annual leave,sick_leaves,best_performance
2,8,5,8,0.5,0,0,0,1,1,3,1,2,30,30,9,7,0,8,0,0
1,5.17,3,2,1.25,0,0,1,16,1,3,2,1,15,16,7,7,9,3,0,0
1,1.83,2,1.83,1.5,0,0,1,17,1,1,0,1,15,15,9,9,0,6,0,0
1,7.92,3,4,0.17,0,0,1,21,1,0,0,0,8,8,5,5,0,3,0,0
1,1.83,2,1.83,2.08,0,0,1,21,1,1,0,1,7,7,4,6,11,2,1,1
1,1.75,2,1.75,6.25,2,0,1,21,1,2,2,0,6,6,1,4,14,12,0,1
1,1.75,2,1.75,1.33,1,0,0,23,0,0,0,0,6,6,7,5,0,0,2,1
1,1.75,2,1.75,5.92,0,0,1,21,1,0,0,0,6,6,1,4,4,10,0,0
1,2.42,2,2.42,1.5,0,0,1,24,1,1,1,0,6,6,3,2,1,8,5,0
1,1.75,2,1.75,1.5,2,0,1,25,1,0,0,0,5,5,3,3,2,5,1,0

In [102]:
train, validate, test = dataH2o.split_frame(ratios=[0.7, 0.15], seed=1) 
test

job_level,job_duration_in_current_job_level,person_level,job_duration_in_current_person_level,job_duration_in_current_branch,Employee_type,Employee_status,gender,age,marital_status_maried(Y/N),number_of_dependences,number_of_dependences (male),number_of_dependences (female),job_duration_as_permanent_worker,job_duration_from_training,branch_rotation,job_rotation,assign_of_otherposition,annual leave,sick_leaves,best_performance
1,1.75,2,1.75,1.5,2,0,1,25,1,0,0,0,5,5,3,3,2,5,1,0
2,2.42,4,2.42,1.5,0,0,0,8,1,3,2,1,24,24,10,9,0,6,2,1
1,1.92,2,1.92,1.5,0,0,1,21,1,1,0,1,5,5,3,3,0,4,0,0
1,0.5,2,0.5,2.33,1,0,1,28,0,0,0,0,2,2,1,2,0,0,0,0
1,2.08,3,0,2.5,0,0,1,25,1,1,0,1,5,5,2,2,4,7,0,0
1,1.83,2,1.83,0.5,1,0,1,26,1,1,1,0,4,4,2,2,0,7,0,0
1,1.83,2,1.83,0.75,2,0,1,25,1,0,0,0,6,6,5,4,5,7,0,0
1,1.75,2,1.75,0.5,0,0,1,27,1,0,0,0,4,4,4,3,0,5,1,0
1,1.58,2,1.58,0.5,1,0,1,23,1,1,0,1,6,6,4,4,10,0,0,0
2,5,5,3,3.17,2,0,0,8,1,2,1,1,22,22,9,7,4,4,0,1

In [10]:
y = 'best_performance'
x = list(dataH2o.columns)
x.remove(y)
print(len(train), len(validate), len(test))

14017 2974 2947

In [11]:
from h2o.estimators.glm import H2OGeneralizedLinearEstimator
glm_fit1 = H2OGeneralizedLinearEstimator(family='binomial', model_id='glm_fit1')
glm_fit1.train(x=x, y=y, training_frame=train)

E:\Anaconda\envs\project1\lib\site-packages\h2o\estimators\estimator_base.py:200: RuntimeWarning: Dropping bad and constant columns: [Employee_status]
  warnings.warn(mesg["message"], RuntimeWarning)

glm Model Build progress: |███████████████████████████████████████████████| 100%

In [12]:
glm_fit2 = H2OGeneralizedLinearEstimator(family='binomial', model_id='glm_fit2', lambda_search=True)
glm_fit2.train(x=x, y=y, training_frame=train, validation_frame=validate)

glm Model Build progress: |███████████████████████████████████████████████| 100%

In [13]:
glm_perf1 = glm_fit1.model_performance(test)
glm_perf2 = glm_fit2.model_performance(test)

In [14]:
# Print model performance
print (glm_perf1)
print (glm_perf2)

ModelMetricsBinomialGLM: glm
** Reported on test data. **

MSE: 0.1111285120800287
RMSE: 0.33335943376486094
LogLoss: 0.3786339103675259
Null degrees of freedom: 2946
Residual degrees of freedom: 2930
Null deviance: 2255.617652904949
Residual deviance: 2231.668267706197
AIC: 2265.668267706197
AUC: 0.570637017618099
AUCPR: 0.1431171658599234
Gini: 0.14127403523619808

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.09704097580217912:

              0       1   Error              Rate
0      0  378.0  2192.0  0.8529   (2192.0/2570.0)
1      1    5.0   372.0  0.0133       (5.0/377.0)
2  Total  383.0  2564.0  0.7455   (2197.0/2947.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.097041     0.252975  332.0
1                        max f2   0.097041     0.456778  332.0
2                  max f0point5   0.138531     0.181980  203.0
3                  max accuracy   0.472156     0.871734    0.0
4                 max precision   0.247196     0.181818   18.0
5                    max recall   0.065533     1.000000  388.0
6               max specificity   0.472156     0.999611    0.0
7              max absolute_mcc   0.097041     0.132922  332.0
8    max min_per_class_accuracy   0.137117     0.552918  208.0
9   max mean_per_class_accuracy   0.111899     0.567147  293.0
10                      max tns   0.472156  2569.000000    0.0
11                      max fns   0.472156   377.000000    0.0
12                      max fps   0.042993  2570.000000  399.0
13                      max tps   0.065533   377.000000  388.0
14                      max tnr   0.472156     0.999611    0.0
15                      max fnr   0.472156     1.000000    0.0
16                      max fpr   0.042993     1.000000  399.0
17                      max tpr   0.065533     1.000000  388.0

Gains/Lift Table: Avg response rate: 12.79 %, avg score: 13.52 %

    group  cumulative_data_fraction  lower_threshold      lift  cumulative_lift  response_rate     score  cumulative_response_rate  cumulative_score  capture_rate  cumulative_capture_rate       gain  cumulative_gain  kolmogorov_smirnov
0       1                  0.010180         0.230980  1.042263         1.042263       0.133333  0.285124                  0.133333          0.285124      0.010610                 0.010610   4.226348         4.226348            0.000493
1       2                  0.020020         0.209934  1.078204         1.059929       0.137931  0.217944                  0.135593          0.252103      0.010610                 0.021220   7.820360         5.992897            0.001376
2       3                  0.030200         0.199056  0.521132         0.878312       0.066667  0.204232                  0.112360          0.235967      0.005305                 0.026525 -47.886826       -12.168808           -0.004214
3       4                  0.040041         0.193122  1.078204         0.927438       0.137931  0.196237                  0.118644          0.226203      0.010610                 0.037135   7.820360        -7.256215           -0.003332
4       5                  0.050221         0.189407  1.302829         1.003531       0.166667  0.190959                  0.128378          0.219059      0.013263                 0.050398  30.282935         0.353072            0.000203
5       6                  0.100102         0.175750  1.276241         1.139424       0.163265  0.181761                  0.145763          0.200473      0.063660                 0.114058  27.624100        13.942364            0.016004
6       7                  0.149983         0.166918  0.904004         1.061128       0.115646  0.170953                  0.135747          0.190655      0.045093                 0.159151  -9.599596         6.112798            0.010513
7       8                  0.200204         0.159965  1.214800         1.099676       0.155405  0.163571                  0.140678          0.183861      0.061008                 0.220159  21.480034         9.967630            0.022883
8       9                  0.299966         0.149200  1.063534         1.087656       0.136054  0.154430                  0.139140          0.174073      0.106101                 0.326260   6.353417         8.765618            0.030151
9      10                  0.400068         0.141625  1.404406         1.166911       0.179661  0.145250                  0.149279          0.166861      0.140584                 0.466844  40.440588        16.691077            0.076571
10     11                  0.500170         0.133978  1.324911         1.198532       0.169492  0.137789                  0.153324          0.161043      0.132626                 0.599469  32.491121        19.853230            0.113866
11     12                  0.599932         0.127491  0.877416         1.145134       0.112245  0.130694                  0.146493          0.155996      0.087533                 0.687003 -12.258431        14.513395            0.099843
12     13                  0.700034         0.119319  1.192420         1.151896       0.152542  0.123470                  0.147358          0.151345      0.119363                 0.806366  19.242009        15.189566            0.121930
13     14                  0.799796         0.108635  1.036946         1.137557       0.132653  0.114557                  0.145524          0.146756      0.103448                 0.909814   3.694581        13.755741            0.126157
14     15                  0.899898         0.089701  0.821445         1.102394       0.105085  0.099936                  0.141026          0.141548      0.082228                 0.992042 -17.855505        10.239407            0.105661
15     16                  1.000000         0.042993  0.079495         1.000000       0.010169  0.078156                  0.127927          0.135202      0.007958                 1.000000 -92.050533         0.000000            0.000000

ModelMetricsBinomialGLM: glm
** Reported on test data. **

MSE: 0.11108971051255467
RMSE: 0.33330123088964836
LogLoss: 0.378685508948101
Null degrees of freedom: 2946
Residual degrees of freedom: 2933
Null deviance: 2255.617652904949
Residual deviance: 2231.9723897401072
AIC: 2259.9723897401072
AUC: 0.5708914324639536
AUCPR: 0.14260727792312505
Gini: 0.14178286492790715

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.11444617652274403:

              0       1   Error              Rate
0      0  622.0  1948.0   0.758   (1948.0/2570.0)
1      1   39.0   338.0  0.1034      (39.0/377.0)
2  Total  661.0  2286.0  0.6742   (1987.0/2947.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.114446     0.253849  301.0
1                        max f2   0.099513     0.455102  341.0
2                  max f0point5   0.137252     0.180408  214.0
3                  max accuracy   0.437078     0.871734    0.0
4                 max precision   0.137252     0.154478  214.0
5                    max recall   0.084930     1.000000  372.0
6               max specificity   0.437078     0.999611    0.0
7              max absolute_mcc   0.098976     0.129742  343.0
8    max min_per_class_accuracy   0.136994     0.551724  215.0
9   max mean_per_class_accuracy   0.114446     0.569288  301.0
10                      max tns   0.437078  2569.000000    0.0
11                      max fns   0.437078   377.000000    0.0
12                      max fps   0.052630  2570.000000  399.0
13                      max tps   0.084930   377.000000  372.0
14                      max tnr   0.437078     0.999611    0.0
15                      max fnr   0.437078     1.000000    0.0
16                      max fpr   0.052630     1.000000  399.0
17                      max tpr   0.084930     1.000000  372.0

Gains/Lift Table: Avg response rate: 12.79 %, avg score: 13.52 %

    group  cumulative_data_fraction  lower_threshold      lift  cumulative_lift  response_rate     score  cumulative_response_rate  cumulative_score  capture_rate  cumulative_capture_rate       gain  cumulative_gain  kolmogorov_smirnov
0       1                  0.010180         0.224876  0.781698         0.781698       0.100000  0.274709                  0.100000          0.274709      0.007958                 0.007958 -21.830239       -21.830239           -0.002548
1       2                  0.020020         0.203441  1.347755         1.059929       0.172414  0.212682                  0.135593          0.244221      0.013263                 0.021220  34.775450         5.992897            0.001376
2       3                  0.030200         0.194800  0.781698         0.966143       0.100000  0.199063                  0.123596          0.228999      0.007958                 0.029178 -21.830239        -3.385688           -0.001172
3       4                  0.040041         0.189347  1.886856         1.192420       0.241379  0.191463                  0.152542          0.219774      0.018568                 0.047745  88.685631        19.242009            0.008835
4       5                  0.050221         0.185034  0.260566         1.003531       0.033333  0.187020                  0.128378          0.213135      0.002653                 0.050398 -73.943413         0.353072            0.000203
5       6                  0.100102         0.172832  1.223064         1.112925       0.156463  0.177972                  0.142373          0.195613      0.061008                 0.111406  22.306429        11.292541            0.012962
6       7                  0.150322         0.164266  0.739444         0.988150       0.094595  0.168154                  0.126411          0.186439      0.037135                 0.148541 -26.055631        -1.184952           -0.002043
7       8                  0.200204         0.158094  1.329418         1.073178       0.170068  0.161043                  0.137288          0.180112      0.066313                 0.214854  32.941771         7.317808            0.016800
8       9                  0.299966         0.148407  1.116711         1.087656       0.142857  0.152946                  0.139140          0.171077      0.111406                 0.326260  11.671088         8.765618            0.030151
9      10                  0.400068         0.140946  1.377908         1.160281       0.176271  0.144255                  0.148431          0.164366      0.137931                 0.464191  37.790766        16.028060            0.073530
10     11                  0.500170         0.133980  1.245417         1.177319       0.159322  0.137484                  0.150611          0.158986      0.124668                 0.588859  24.541654        17.731934            0.101700
11     12                  0.599932         0.128344  1.169888         1.176084       0.149660  0.131121                  0.150452          0.154352      0.116711                 0.705570  16.988758        17.608351            0.121134
12     13                  0.700034         0.120492  0.980434         1.148107       0.125424  0.124460                  0.146873          0.150078      0.098143                 0.803714  -1.956571        14.810653            0.118889
13     14                  0.799796         0.110637  1.036946         1.134241       0.132653  0.116352                  0.145100          0.145871      0.103448                 0.907162   3.694581        13.424091            0.123115
14     15                  0.899898         0.093269  0.874441         1.105342       0.111864  0.102709                  0.141403          0.141070      0.087533                 0.994695 -12.555860        10.534165            0.108703
15     16                  1.000000         0.052630  0.052996         1.000000       0.006780  0.082805                  0.127927          0.135237      0.005305                 1.000000 -94.700355         0.000000            0.000000

In [15]:
print (glm_perf1.auc())
print (glm_perf2.auc())

0.570637017618099
0.5708914324639536

In [16]:
print (glm_fit2.auc(train=True))
print (glm_fit2.auc(valid=True))

0.5725038364227057
0.5697689401090126

In [17]:
from h2o.estimators.random_forest import H2ORandomForestEstimator
rf_fit1 = H2ORandomForestEstimator(model_id='rf_fit1', seed=1)

In [18]:
rf_fit1.train(x=x, y=y, training_frame=train)

E:\Anaconda\envs\project1\lib\site-packages\h2o\estimators\estimator_base.py:200: RuntimeWarning: Dropping bad and constant columns: [Employee_status]
  warnings.warn(mesg["message"], RuntimeWarning)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [19]:
rf_fit2 = H2ORandomForestEstimator(model_id='rf_fit2', ntrees=100, seed=1)
rf_fit2.train(x=x, y=y, training_frame=train)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [20]:
rf_perf1 = rf_fit1.model_performance(test)
rf_perf2 = rf_fit2.model_performance(test)

In [21]:
print (rf_perf1.auc())
print (rf_perf2.auc())

0.5989761479631331
0.6088095655853606

In [22]:
rf_fit3 = H2ORandomForestEstimator(model_id='rf_fit3', seed=1, nfolds=5)
rf_fit3.train(x=x, y=y, training_frame=dataH2o)

drf Model Build progress: |███████████████████████████████████████████████| 100%

In [23]:
print (rf_fit3.auc(xval=True))

0.602689980284901

In [24]:
from h2o.estimators.gbm import H2OGradientBoostingEstimator

In [25]:
gbm_fit1 = H2OGradientBoostingEstimator(model_id='gbm_fit1', seed=1)
gbm_fit1.train(x=x, y=y, training_frame=train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [26]:
gbm_fit2 = H2OGradientBoostingEstimator(model_id='gbm_fit2', ntrees=500, seed=1)
gbm_fit2.train(x=x, y=y, training_frame=train)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [27]:
# Now let's use early stopping to find optimal ntrees

gbm_fit3 = H2OGradientBoostingEstimator(model_id='gbm_fit3', 
                                        ntrees=500, 
                                        score_tree_interval=5,     #used for early stopping
                                        stopping_rounds=3,         #used for early stopping
                                        stopping_metric='AUC',     #used for early stopping
                                        stopping_tolerance=0.0005, #used for early stopping
                                        seed=1)

# The use of a validation_frame is recommended with using early stopping
gbm_fit3.train(x=x, y=y, training_frame=train, validation_frame=validate)

gbm Model Build progress: |███████████████████████████████████████████████| 100%

In [28]:
gbm_perf1 = gbm_fit1.model_performance(test)
gbm_perf2 = gbm_fit2.model_performance(test)
gbm_perf3 = gbm_fit3.model_performance(test)

In [29]:
print (gbm_perf1.auc())
print (gbm_perf2.auc())
print (gbm_perf3.auc())

0.6151425858456585
0.5967204739444106
0.6098411584390385

In [154]:
gbm_fit2.scoring_history()

                 timestamp    duration  number_of_trees  training_rmse  training_logloss  training_auc  training_pr_auc  training_lift  training_classification_error
0      2020-12-17 12:37:30   0.044 sec              0.0       0.342613          0.397330      0.500000         0.135835       1.000000                       0.864165
1      2020-12-17 12:37:30   0.077 sec              1.0       0.341396          0.393827      0.635443         0.212254       3.013920                       0.544125
2      2020-12-17 12:37:30   0.108 sec              2.0       0.340417          0.391027      0.638446         0.215114       3.067446                       0.393593
3      2020-12-17 12:37:30   0.124 sec              3.0       0.339608          0.388679      0.644095         0.217388       3.067446                       0.493330
4      2020-12-17 12:37:30   0.155 sec              4.0       0.338915          0.386636      0.645246         0.217994       3.067446                       0.485125
.. ..                  ...         ...              ...            ...               ...           ...              ...            ...                            ...
92     2020-12-17 12:37:34   3.868 sec             92.0       0.322037          0.344456      0.775586         0.409938       6.578692                       0.208318
93     2020-12-17 12:37:34   3.912 sec             93.0       0.321935          0.344245      0.776297         0.410730       6.526480                       0.208889
94     2020-12-17 12:37:34   3.961 sec             94.0       0.321711          0.343770      0.778137         0.413628       6.526480                       0.215239
95     2020-12-17 12:37:34   4.006 sec             95.0       0.321637          0.343618      0.778441         0.413843       6.526480                       0.216594
96     2020-12-17 12:37:38   7.883 sec            500.0       0.304440          0.310259      0.846571         0.562965       7.361870                       0.126489

[97 rows x 10 columns]

In [155]:
from h2o.estimators.deeplearning import H2ODeepLearningEstimator

In [156]:
dl_fit1 = H2ODeepLearningEstimator(model_id='dl_fit1', seed=1)
dl_fit1.train(x=x, y=y, training_frame=train)

E:\Anaconda\envs\project1\lib\site-packages\h2o\estimators\estimator_base.py:200: RuntimeWarning: Dropping bad and constant columns: [Employee_status]
  warnings.warn(mesg["message"], RuntimeWarning)

deeplearning Model Build progress: |██████████████████████████████████████| 100%

In [157]:
dl_fit2 = H2ODeepLearningEstimator(model_id='dl_fit2', 
                                   epochs=20, 
                                   hidden=[10,10], 
                                   stopping_rounds=0,  #disable early stopping
                                   seed=1)
dl_fit2.train(x=x, y=y, training_frame=train)

deeplearning Model Build progress: |██████████████████████████████████████| 100%

In [158]:
dl_fit3 = H2ODeepLearningEstimator(model_id='dl_fit3', 
                                   epochs=20, 
                                   hidden=[10,10],
                                   score_interval=1,          #used for early stopping
                                   stopping_rounds=3,         #used for early stopping
                                   stopping_metric='AUC',     #used for early stopping
                                   stopping_tolerance=0.0005, #used for early stopping
                                   seed=1)
dl_fit3.train(x=x, y=y, training_frame=train, validation_frame=validate)

deeplearning Model Build progress: |██████████████████████████████████████| 100%

In [159]:
dl_perf1 = dl_fit1.model_performance(test)
dl_perf2 = dl_fit2.model_performance(test)
dl_perf3 = dl_fit3.model_performance(test)

In [160]:
print (dl_perf1.auc())
print (dl_perf2.auc())
print (dl_perf3.auc())

0.6019873257026082
0.5681754378722043
0.562527221872452

In [45]:
real_p = h2o.H2OFrame(pred_real_data)
res = gbm_fit2.predict(real_p)

Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm prediction progress: |████████████████████████████████████████████████| 100%

In [162]:
df_res = res.as_data_frame()
df_res = pd.DataFrame(df_res['p1'])
df_res.columns = ['Best Performance']
df_res['index'] = df_res.index
df_res = df_res[['index', 'Best Performance']]
df_res.head()
#print(df_res.max())

   index  Best Performance
0      0          0.088056
1      1          0.157541
2      2          0.198249
3      3          0.150630
4      4          0.117605

In [1]:
df_res.to_csv('pred_result_with_h2o.csv', index=False)

NameError: name 'df_res' is not defined